### PR TITLE
[Add]: LeetCode Problems 2800 - 2899

### PR DESCRIPTION
**Pull request by iamanolive**
resolves issue #277

### CODE REVIEW

**Comment by iamanolive** [comment]
hi @Ajay-Dhangar i just noticed that you labeled some of the leetcode problem pull requests as level1 and some of level2. but theyre all of the same difficulty so why are they labelled differently?

**Comment by Ajay-Dhangar** [comment]
> hi @Ajay-Dhangar i just noticed that you labeled some of the leetcode problem pull requests as level1 and some of level2. but theyre all of the same difficulty so why are they labelled differently?

I just received some notifications and information from GSSOC'24. We can't put it on a large scale, but you can watch the full [video](https://www.loom.com/share/2ff2899f7bbf418d9168599094ffe131?sid=f1120a30-3327-4d54-be6a-4630dd958355) for more details.

**Comment by Ajay-Dhangar** [comment]
> > hi @Ajay-Dhangar i just noticed that you labeled some of the leetcode problem pull requests as level1 and some of level2. but theyre all of the same difficulty so why are they labelled differently?
> 
> I just received some notifications and information from GSSOC'24. We can't put it on a large scale, but you can watch the full [video](https://www.loom.com/share/2ff2899f7bbf418d9168599094ffe131?sid=f1120a30-3327-4d54-be6a-4630dd958355) for more details.

I also assign a level based on your response and the time you take to complete tasks. If you complete a task quickly, such as within a day, I will assign a higher level. If you take more time for simple tasks, I will assign a different level based on your performance.

**Review by Ajay-Dhangar — APPROVED** [review]
Done

**Comment by iamanolive** [comment]
oh ok got it! thank you so much for clarifying @Ajay-Dhangar

**Pull request merged**
