### PR TITLE
Symmetric tree solution

### PR DESCRIPTION
**Pull request by Vipullakum007**
## Related Issue

Fixed : #425 

## Description

Added solution for "Same Tree " under leetcode solution > 0100-0199

## Type of PR

- [ ] Bug fix
- [x] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

## Screenshots / Videos (if applicable)

Screenshot (548)
Screenshot (549)
Screenshot (550)

Screenshot (551)
Screenshot (552)

Screenshot (553)

## Checklist
- [x] I have performed a self-review of my code.
- [x] I have read and followed the Contribution Guidelines.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [x] I have commented my code, particularly in hard-to-understand areas.

## Additional Context

[Include any additional information or context that might be helpful for reviewers.]

## Resources for Guidance

Here are some resources that may be helpful as you contribute to CodeHarborHub:
- [Code Harbor Hub Community Features](https://www.codeharborhub.live/community/features)
- [Docusaurus Documentation](https://docusaurus.io/docs/create-doc)
- [React.js Documentation](https://legacy.reactjs.org/docs/getting-started.html)
- [Markdown Guide](https://www.markdownguide.org/)
- [MDX Documentation](https://mdxjs.com/docs/)
- [Mermaid Documentation](https://mermaid.js.org/)

**Resources for DSA Features on Our Site:**

- Tabs: [Switch Languages](https://www.codeharborhub.live/community/features#multi-language-support-code-blocks)
- [Line Numbering](https://www.codeharborhub.live/community/features#line-numbering)
- [Math Equations](https://www.codeharborhub.live/community/features#math-equations-with-katex)

### CODE REVIEW

**Comment by Vipullakum007** [comment]
hey @Ajay-Dhangar , please make it level 3 because i have added 2 Approach

**Comment by Vipullakum007** [comment]
hey @Ajay-Dhangar  if you want , please make it level 3 because i have added 2 Approach

**Review by Ajay-Dhangar — APPROVED** [review]
Done

**Comment by Ajay-Dhangar** [comment]
> hey @Ajay-Dhangar if you want , please make it level 3 because i have added 2 Approach

but I can't assign to you level 3 if you want to then try to improvement code. Please follow our structure, similar to the source code of the [Two Sum problem](https://github.com/CodeHarborHub/codeharborhub/blob/main/dsa-solutions/lc-solutions/0000-0099/0001-two-sum.md?plain=1), to ensure better understanding for everyone. And [Live Preview](https://www.codeharborhub.live/dsa-solutions/lc-solutions/0000-0099/two-sum)

**Pull request merged**
