### PR TITLE
adding Express to the sidebar and making required Directories

### PR DESCRIPTION
**Pull request by AryanAg08**
## Description

Adding Required Directory for ExpressJs and Updating SideBar

## Type of PR

- [ ] Bug fix
- Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

### CODE REVIEW

**Review by Ajay-Dhangar — CHANGES_REQUESTED** [review]
can you write in `docs` directory for tutorial's, not in others

**Comment by AryanAg08** [comment]
> can you write in `docs` directory for tutorial's, not in others

I thought I have to write it in Web Dev Section ?

**Comment by Ajay-Dhangar** [comment]
> > can you write in `docs` directory for tutorial's, not in others
> 
> I thought I have to write it in Web Dev Section ?

you can be change code for Docs.

**Comment by Ajay-Dhangar** [comment]
you can try to use `git pull origin main` or sync our main repo for latest code and work on it.

**Comment by Ajay-Dhangar** [comment]
create new issues for this

**Pull request closed without merging**
