### PR TITLE
Create 0001-0100.md

### PR DESCRIPTION
**Pull request by agastya3636**
added 100 basic problems

## Related Issue #385 

[Cite any related issue(s) this pull request addresses. If none, simply state "None”]

## Description

[Please include a brief description of the changes or features added]

## Type of PR

- [ ] Bug fix
- [x] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

## Screenshots / Videos (if applicable)

[Attach any relevant screenshots or videos demonstrating the changes]

## Checklist
- [x] I have performed a self-review of my code.
- [x] I have read and followed the Contribution Guidelines.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [x] I have commented my code, particularly in hard-to-understand areas.

## Additional Context

[Include any additional information or context that might be helpful for reviewers.]

## Resources for Guidance

Here are some resources that may be helpful as you contribute to CodeHarborHub:
- [Code Harbor Hub Community Features](https://www.codeharborhub.live/community/features)
- [Docusaurus Documentation](https://docusaurus.io/docs/create-doc)
- [React.js Documentation](https://legacy.reactjs.org/docs/getting-started.html)
- [Markdown Guide](https://www.markdownguide.org/)
- [MDX Documentation](https://mdxjs.com/docs/)
- [Mermaid Documentation](https://mermaid.js.org/)

**Resources for DSA Features on Our Site:**

- Tabs: [Switch Languages](https://www.codeharborhub.live/community/features#multi-language-support-code-blocks)
- [Line Numbering](https://www.codeharborhub.live/community/features#line-numbering)
- [Math Equations](https://www.codeharborhub.live/community/features#math-equations-with-katex)

### CODE REVIEW

**Review by Ajay-Dhangar — CHANGES_REQUESTED** [review]
Follow structure like https://github.com/CodeHarborHub/codeharborhub/blob/main/dsa-problems/gfg-problems/basic/problems.md?plain=1

**Comment by agastya3636** [comment]
@Ajay-Dhangar does i have to 
 {
    "problemName": "1. Inorder Traversal",
    "difficulty": "basic",
    "leetCodeLink": "https://www.geeksforgeeks.org/problems/inorder-traversal/0",
    "solutionLink": "#"
  }

but it was gfg URL not leetCodeLink

**Comment by Ajay-Dhangar** [comment]
> @Ajay-Dhangar does i have to { "problemName": "1. Inorder Traversal", "difficulty": "basic", "leetCodeLink": "https://www.geeksforgeeks.org/problems/inorder-traversal/0", "solutionLink": "#" }
> 
> but it was gfg URL not leetCodeLink

No problem! We use props to pass data, and it's only a name. For GFG, we are currently using LC, and you can use it as well. I will update and set up the code for GFG and others, so don't worry and give it a try.

**Comment by agastya3636** [comment]
ok then i will correct it

**Comment by agastya3636** [comment]
@Ajay-Dhangar Please check it

**Review by Ajay-Dhangar — APPROVED** [review]
Done

**Comment by sanjay-kv** [comment]
image


taking out 150 points due to guidelines. 200 points on this repo will be awarded for contribution. 
any technical work added wont be counted.

**Pull request merged**
