### PR TITLE
Create 0002-Add-Two-Numbers.md

### PR DESCRIPTION
**Pull request by AmrutaJayanti**
## Description

Added Solution to 0002 - Add Two Numbers

###Issues Related:

Closes: #299 

## Type of PR

- [ ] Bug fix
- [ ] Feature enhancement
- [ ] Documentation update
- [x] Other (specify): Adding Solution

## Checklist
- [x] I have performed a self-review of my code.
- [x] I have read and followed the Contribution Guidelines.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [x] I have commented my code, particularly in hard-to-understand areas.

## Resources for Guidance

Here are some resources that may be helpful as you contribute to CodeHarborHub:
- [Code Harbor Hub Community Features](https://www.codeharborhub.live/community/features)
- [Docusaurus Documentation](https://docusaurus.io/docs/create-doc)
- [React.js Documentation](https://legacy.reactjs.org/docs/getting-started.html)
- [Markdown Guide](https://www.markdownguide.org/)
- [MDX Documentation](https://mdxjs.com/docs/)
- [Mermaid Documentation](https://mermaid.js.org/)

**Resources for DSA Features on Our Site:**

- Tabs: [Switch Languages](https://www.codeharborhub.live/community/features#multi-language-support-code-blocks)
- [Line Numbering](https://www.codeharborhub.live/community/features#line-numbering)
- [Math Equations](https://www.codeharborhub.live/community/features#math-equations-with-katex)

### CODE REVIEW

**Review by Ajay-Dhangar — CHANGES_REQUESTED** [review]
Your Structure is not a good So, can you follow our structure like [Source Code of Two Sum Problem](https://github.com/CodeHarborHub/codeharborhub/blob/main/dsa-solutions/lc-solutions/0000-0099/0001-two-sum.md?plain=1) and also, make similar to this for good and better understanding to all

**Comment by AmrutaJayanti** [comment]
@Ajay-Dhangar I made the changes . Please approve

**Review by Ajay-Dhangar — APPROVED** [review]
Okay, Done and you can be put this page reference in your leetcode solution for good to learners

**Comment by iamanolive** [comment]
hi @Ajay-Dhangar i had been assigned this issue to work on a couple days back. please clarify.

**Pull request merged**
