### PR TITLE
Added issues template for documentation issues 

### LINKED ISSUE #198: Add issues template for documentation issues
I would like to add a issues template for documentation issues in this repository. I believe that having a standardised template will help streamline the contribution process, ensuring that all necessary information is included and making it easier for maintainers to review issues.

Could you please assign this issue to me under GSSOC'24.

### PR DESCRIPTION
**Pull request by suhanipaliwal**
## Related Issue
Closes #198 

## Type of PR

- [ ] Bug fix
- [ ] Feature enhancement
- [x] Documentation update
- [ ] Other (specify): _______________

## Checklist
- [x] I have performed a self-review of my code.
- [x] I have read and followed the Contribution Guidelines.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [x] I have commented my code, particularly in hard-to-understand areas.

## Resources for Guidance

Here are some resources that may be helpful as you contribute to CodeHarborHub:
- [Code Harbor Hub Community Features](https://www.codeharborhub.live/community/features)
- [Docusaurus Documentation](https://docusaurus.io/docs/create-doc)
- [React.js Documentation](https://legacy.reactjs.org/docs/getting-started.html)
- [Markdown Guide](https://www.markdownguide.org/)
- [MDX Documentation](https://mdxjs.com/docs/)
- [Mermaid Documentation](https://mermaid.js.org/)

**Resources for DSA Features on Our Site:**

- Tabs: [Switch Languages](https://www.codeharborhub.live/community/features#multi-language-support-code-blocks)
- [Line Numbering](https://www.codeharborhub.live/community/features#line-numbering)
- [Math Equations](https://www.codeharborhub.live/community/features#math-equations-with-katex)

### CODE REVIEW

**Review by Ajay-Dhangar — APPROVED** [review]
Done

**Comment by suhanipaliwal** [comment]
Could you please add the label of level1

**Comment by suhanipaliwal** [comment]
Could you please add the label of level1

**Comment by suhanipaliwal** [comment]
Could you please add the label of level1

**Pull request merged**
