### PR TITLE
youtube video spilling over to the fetures section on big screens

### PR DESCRIPTION
**Pull request by Stiffpixels**
fixed the responsive bug of youtube video overflowing to the features of codeHarborHub  
* from:
image

* to:
image

### CODE REVIEW

**Review by Ajay-Dhangar — CHANGES_REQUESTED** [review]
**issue:** Avoid non-native interactive elements. If using native HTML is not possible, add an appropriate role and support for tabbing, mouse, keyboard, and touch inputs to an interactive content element.

### How can I fix it?

The simplest and most recommended way is to replace the non-interactive elements with interactive ones. If for some reason you can’t replace the non-interactive element, you can add an interactive `role` attribute to it and manually manage its keyboard event handlers and focus. Common interactive roles include `button`, `link`, `checkbox`, `menuitem`, `menuitemcheckbox`, `menuitemradio`, `option`, `radio`, `searchbox`, `switch`, and `textbox`.

**Noncompliant code example**

```jsx
<div onClick={() => {}} />; // Noncompliant
```

**Compliant solution**

```jsx
<div onClick={() => {}} role="button" />;
```

**Review by Stiffpixels — COMMENTED** [review]
reviewed the change for code formatting.

**Comment by Stiffpixels** [comment]
do I need to create a new PR or can the changes directly be made here? @Ajay-Dhangar

**Comment by Ajay-Dhangar** [comment]
> do I need to create a new PR or can the changes directly be made here?

If you're confident in addressing related issues, please go ahead. Otherwise, my suggestion is to start fresh and follow all syntax to prevent any new issues from arising.

**Comment by Stiffpixels** [comment]
> > do I need to create a new PR or can the changes directly be made here?
> 
> If you're confident in addressing related issues, please go ahead. Otherwise, my suggestion is to start fresh and follow all syntax to prevent any new issues from arising.

The code that is causing the issue is actually present in the source repo as well.
image
image

**Comment by Ajay-Dhangar** [comment]
> > > do I need to create a new PR or can the changes directly be made here?
> > 
> > 
> > If you're confident in addressing related issues, please go ahead. Otherwise, my suggestion is to start fresh and follow all syntax to prevent any new issues from arising.
> 
> The code that is causing the issue is actually present in the source repo as well. So what should I do the code was there when I cloned the github repo.
> 
> image image

You can try other because I need to resolve it and I will do update this on my side. So, you can also work on other UI pard as you want to need on our site

**Comment by Stiffpixels** [comment]
ok I will make another pull request

**Pull request closed without merging**
