### PR TITLE
Added pull_request_template.md

### LINKED ISSUE #142: Add PR template
I would like to add a pull request template for this repository. I believe that having a standardized template will help streamline the contribution process, ensuring that all necessary information is included and making it easier for maintainers to review and merge pull requests.

Could you please assign this issue to me under GSSOC'24.

### PR DESCRIPTION
**Pull request by suhanipaliwal**
Fixes #142

### CODE REVIEW

**Review by Ajay-Dhangar — APPROVED** [review]

**Review by Ajay-Dhangar — APPROVED** [review]

**Review by Ajay-Dhangar — APPROVED** [review]
Done

**Comment by suhanipaliwal** [comment]
Please add the labels of gssoc and level2 on this pull request as well according to gssoc latest guidelines.

**Comment by suhanipaliwal** [comment]
Please add the labels of gssoc and level2 on this pull request and assign me this pull request as well according to gssoc latest guidelines.

**Comment by suhanipaliwal** [comment]
Could you please add the label of gssoc and level1

**Comment by suhanipaliwal** [comment]
Could you please add the label of gssoc and level1

**Pull request merged**
